<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Decode</name>
   <tag></tag>
   <elementGuidId>7e2e4d78-5ce7-4887-a7c6-315fe1bb9600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Decode')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.w-full.py-2.px-4.rounded-md.activeLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Decode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98cc975f-ddcd-4548-a1cf-5a2274871ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/base64-decode</value>
      <webElementGuid>d83deb1e-d1e0-4cf8-a4dd-9d8b2779b544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-4 rounded-md activeLink</value>
      <webElementGuid>8b0203ee-e231-443d-b793-7eef3ec8a5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/base64-decode</value>
      <webElementGuid>ba7a0212-dfc4-4e02-b56a-2e60ecb9e869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Decode</value>
      <webElementGuid>44aca848-8d4b-47e8-bbaf-ebbf2483d2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;flex&quot;]/app-navbar[@class=&quot;w-64 h-screen fixed&quot;]/nav[@class=&quot;shadow-sm fixed left-0 h-full bg-white z-50 w-72 px-8 py-10&quot;]/div[@class=&quot;container text-base mx-auto flex flex-col mt-12&quot;]/div[@class=&quot;flex flex-col mb-1 mt-2&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/a[@class=&quot;w-full py-2 px-4 rounded-md activeLink&quot;]</value>
      <webElementGuid>3c9a3cd8-e957-4c4c-beb9-938a0e43b99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Decode')]</value>
      <webElementGuid>33cc9648-e44b-4a41-ac18-6b5d18b4bc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encode'])[1]/following::a[1]</value>
      <webElementGuid>3b86670c-110b-4413-b62d-bb04ce66396a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>2b3023a7-a844-4955-8c09-08f90ee5b2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encode by File'])[1]/preceding::a[1]</value>
      <webElementGuid>fadcfb2c-9714-4c7a-a47c-1e4c18cf3bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring Filter'])[1]/preceding::a[2]</value>
      <webElementGuid>7289e024-508d-4d61-818b-c99cef91d491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Decode']/parent::*</value>
      <webElementGuid>45c6965e-c8ce-4ef7-a583-87ea76a27b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/base64-decode')]</value>
      <webElementGuid>fd4ba21c-6ae2-46d4-a205-4c1eb22302ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>20ac173a-47fa-40a7-8031-525d85184ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/base64-decode' and (text() = 'Decode' or . = 'Decode')]</value>
      <webElementGuid>f242b297-37c5-43a6-b827-f7de02018fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
