<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Encode</name>
   <tag></tag>
   <elementGuidId>c6cb6ea4-2788-497c-9b42-7472f7162e12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Encode')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.w-full.py-2.px-4.rounded-md.activeLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Encode&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>971b06b9-47b7-41b7-aa35-e1a61e097199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/base64-encode</value>
      <webElementGuid>143df859-5323-4e13-8d16-69a968ad39a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-4 rounded-md activeLink</value>
      <webElementGuid>edb115bc-7f4a-40b4-8dfb-46f860936dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/base64-encode</value>
      <webElementGuid>86aa2990-0428-4f4e-8757-4d5d231cab28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Encode</value>
      <webElementGuid>f04905fc-8f4a-4f09-ba6d-a0d10173ce27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;flex&quot;]/app-navbar[@class=&quot;w-64 h-screen fixed&quot;]/nav[@class=&quot;shadow-sm fixed left-0 h-full bg-white z-50 w-72 px-8 py-10&quot;]/div[@class=&quot;container text-base mx-auto flex flex-col mt-12&quot;]/div[@class=&quot;flex flex-col mb-1 mt-2&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/a[@class=&quot;w-full py-2 px-4 rounded-md activeLink&quot;]</value>
      <webElementGuid>6cf8d29c-4dbe-4ec5-9a1b-4d5af853c599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Encode')]</value>
      <webElementGuid>2a971ac2-a456-47f9-93dc-2b1bbb009e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>8ac11b65-10ab-43e1-a8b4-a11598deceef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decode'])[1]/preceding::a[1]</value>
      <webElementGuid>2954a8f9-9556-46a0-a575-5d8df5481de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encode by File'])[1]/preceding::a[2]</value>
      <webElementGuid>65f976ee-7534-4f14-81ec-0c369f9983ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Encode']/parent::*</value>
      <webElementGuid>7cf973ea-d6b9-48da-878a-3965cf791730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/base64-encode')]</value>
      <webElementGuid>10eb7f7d-2d04-4938-9d61-0362b373ee3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>616f418d-1ec9-41b6-b95a-62472bef41ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/base64-encode' and (text() = 'Encode' or . = 'Encode')]</value>
      <webElementGuid>dd123ee9-4972-459f-b6eb-9ca2d9e6c979</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
